name: dart_read_win1254ru
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: stekolschikov <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  synchronized: ^1.5.1
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
